### PR TITLE
Fix unstable tests for AudioContext

### LINKED ISSUE #432: Unstable tests in tests/online.rs
The event loop has unpredictable timings. Also the sleeps commands to measure progress of current time sometimes do not suffice

### PR DESCRIPTION
**Pull request by orottier**
Fixes #432

### CODE REVIEW

File: tests/online.rs [hunk 1]
```diff
@@ -8,13 +8,41 @@ use web_audio_api::context::{
 };
 use web_audio_api::node::AudioNode;
 
-use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
 use std::thread;
 use std::time::Duration;
 use web_audio_api::MAX_CHANNELS;
 
+const TEST_TIMEOUT: Duration = Duration::from_secs(1);
```
Comment (orottier) [inline tests/online.rs]:
```suggestion
const TEST_TIMEOUT: Duration = Duration::from_secs(2);
```

Funny we had another failure on 1 second, lets try double
